"""empty message

Revision ID: 93bdd4de4761
Revises: 25db4e6b19ec
Create Date: 2022-11-04 11:15:55.928351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93bdd4de4761'
down_revision = '25db4e6b19ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=25), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('token', sa.String(length=260), nullable=False),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('admin_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('hall',
    sa.Column('hall_name', sa.String(length=3), autoincrement=False, nullable=False),
    sa.Column('row_amount', sa.Integer(), nullable=False),
    sa.Column('seat_amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('hall_name')
    )
    op.create_table('movie',
    sa.Column('movie_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('poster_url', sa.String(length=400), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('created_year', sa.DATE(), nullable=False),
    sa.Column('long', sa.Integer(), nullable=False),
    sa.Column('age_restriction', sa.Integer(), nullable=False),
    sa.Column('trailer_url', sa.String(length=150), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=False),
    sa.Column('director', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('movie_id'),
    sa.UniqueConstraint('movie_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=25), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('token', sa.String(length=260), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('phone', sa.String(length=13), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('scheduled_movie',
    sa.Column('scheduledmovie_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DATETIME(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('hall', sa.String(length=3), nullable=False),
    sa.Column('type', sa.Enum('2D', '3D', '4D'), nullable=False),
    sa.Column('language', sa.String(length=40), nullable=False),
    sa.Column('id_movie', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hall'], ['hall.hall_name'], ),
    sa.ForeignKeyConstraint(['id_movie'], ['movie.movie_id'], ),
    sa.PrimaryKeyConstraint('scheduledmovie_id'),
    sa.UniqueConstraint('scheduledmovie_id')
    )
    op.create_table('ticket',
    sa.Column('ticket_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('row_n', sa.Integer(), nullable=False),
    sa.Column('seat_n', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_scheduledmovie', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_scheduledmovie'], ['scheduled_movie.scheduledmovie_id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('ticket_id'),
    sa.UniqueConstraint('ticket_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_table('scheduled_movie')
    op.drop_table('user')
    op.drop_table('movie')
    op.drop_table('hall')
    op.drop_table('admin')
    # ### end Alembic commands ###
