"""empty message

Revision ID: add5add9cce8
Revises: e5cf7814a926
Create Date: 2022-11-03 12:05:54.603217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'add5add9cce8'
down_revision = 'e5cf7814a926'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheduled_movie', 'type',
               existing_type=mysql.ENUM('2D', '3D', '4D'),
               nullable=False)
    op.add_column('ticket', sa.Column('id_user', sa.Integer(), nullable=False))
    op.drop_constraint('ticket_ibfk_1', 'ticket', type_='foreignkey')
    op.create_foreign_key(None, 'ticket', 'user', ['id_user'], ['user_id'])
    op.drop_column('ticket', 'id_language')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('id_language', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.create_foreign_key('ticket_ibfk_1', 'ticket', 'user', ['id_language'], ['user_id'])
    op.drop_column('ticket', 'id_user')
    op.alter_column('scheduled_movie', 'type',
               existing_type=mysql.ENUM('2D', '3D', '4D'),
               nullable=True)
    # ### end Alembic commands ###
