"""empty message

Revision ID: e14ca240c37b
Revises: fd7d2e4b1ac0
Create Date: 2022-11-21 10:07:18.548680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e14ca240c37b'
down_revision = 'fd7d2e4b1ac0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('details', sa.String(length=120), nullable=True))
    op.drop_index('ticket_id', table_name='ticket')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ticket_id', 'ticket', ['ticket_id'], unique=False)
    op.drop_column('ticket', 'details')
    # ### end Alembic commands ###
