"""empty message

Revision ID: e5cf7814a926
Revises: 81ba2ba97a86
Create Date: 2022-11-03 11:36:46.767730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5cf7814a926'
down_revision = '81ba2ba97a86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('genre_id', table_name='genre')
    op.drop_index('name', table_name='genre')
    op.drop_table('genre')
    op.drop_index('director_id', table_name='director')
    op.drop_index('name', table_name='director')
    op.drop_table('director')
    op.drop_index('language_id', table_name='language')
    op.drop_index('name', table_name='language')
    op.drop_table('language')
    op.drop_index('country_id', table_name='country')
    op.drop_index('name', table_name='country')
    op.drop_table('country')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('country_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('country_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'country', ['name'], unique=False)
    op.create_index('country_id', 'country', ['country_id'], unique=False)
    op.create_table('language',
    sa.Column('language_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('language_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'language', ['name'], unique=False)
    op.create_index('language_id', 'language', ['language_id'], unique=False)
    op.create_table('director',
    sa.Column('director_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('director_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'director', ['name'], unique=False)
    op.create_index('director_id', 'director', ['director_id'], unique=False)
    op.create_table('genre',
    sa.Column('genre_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('genre_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'genre', ['name'], unique=False)
    op.create_index('genre_id', 'genre', ['genre_id'], unique=False)
    # ### end Alembic commands ###
